### ISSUE TITLE
Panic parsing digest

### ISSUE THREAD

**Issue by pubg-beege** [cloudfoundry/bosh-utils#32]
Using concourse/concourse-deployment/cluster/concourse.yml in the following deploy command:
```
bosh deploy bosh-manifests/concourse/concourse.yml \
    -d concourse \
    -o bosh-manifests/concourse/operations/basic-auth.yml \
    --vars-store=creds.yml \
    -v deployment_name=concourse \
    -v external_url=<redacted> \
    -v network_name=ops_services \
    -v web_vm_type=concourse_web \
    -v db_vm_type=concourse_db \
    -v db_persistent_disk_type=large \
    -v worker_vm_type=concourse_worker \
    -v concourse_version=3.8.0 \
    -v postgres_version=24 \
    -v garden_runc_version=1.11.0
```

I get the following error with all three releases in that deploy manifest:
```
Error: panic: Parsing multiple digest: Unable to parse digest string. Digest and algorithm key can only contain alpha-numeric characters.

goroutine 1 [running]:
panic(0x51cc80, 0xc420016590)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cloudfoundry/bosh-utils/crypto.MustParseMultipleDigest(0x7fff811ad838, 0x12, 0x10000c420041c70, 0x5ed126dd0000005d, 0x2)
	/tmp/build/020a9e9e/gopath/src/github.com/cloudfoundry/bosh-utils/crypto/multiple_digest.go:29 +0x12e
main.MultiDigestCommand.Execute(0x7fff811ad7ef, 0x48, 0x7fff811ad838, 0x12, 0xc42000e570, 0x0, 0x3, 0x488a01, 0x7efe7adfc000)
	/tmp/build/020a9e9e/gopath/src/github.com/cloudfoundry/bosh-utils/main/verify_multidigest.go:52 +0x39
main.(*MultiDigestCommand).Execute(0xc420010370, 0xc42000e570, 0x0, 0x3, 0x1, 0x3)
	<autogenerated>:1 +0x8b
github.com/cloudfoundry/bosh-utils/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc4200180c0, 0xc42000a210, 0x3, 0x3, 0xc420086000, 0xc4200180c0, 0x7fff811ad7c8, 0x0, 0x0)
	/tmp/build/020a9e9e/gopath/src/github.com/cloudfoundry/bosh-utils/vendor/github.com/jessevdk/go-flags/parser.go:316 +0x8e6
github.com/cloudfoundry/bosh-utils/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc4200180c0, 0xc420010370, 0x16, 0xc4200180c0, 0x4a3b01, 0xc420010370)
	/tmp/build/020a9e9e/gopath/src/github.com/cloudfoundry/bosh-utils/vendor/github.com/jessevdk/go-flags/parser.go:186 +0x74
github.com/cloudfoundry/bosh-utils/vendor/github.com/jessevdk/go-flags.Parse(0x516100, 0xc420010370, 0x54f8bc, 0x28, 0x5dd1a0, 0xc420016370, 0xc4200001a0)
	/tmp/build/020a9e9e/gopath/src/github.com/cloudfoundry/bosh-utils/vendor/github.com/jessevdk/go-flags/parser.go:133 +0x4c
main.main()
	/tmp/build/020a9e9e/gopath/src/github.com/cloudfoundry/bosh-utils/main/verify_multidigest.go:29 +0x77
```

I understand this may be an issue with the concourse deploy manifest, but I'm not sure the full stack trace is necessary.

**Comment by cppforlife** [comment]
@pubg-beege could you include releases section of the manifest?

> I understand this may be an issue with the concourse deploy manifest, but I'm not sure the full stack trace is necessary.

are you proposing to remove the stacktrace from the error msg?
